services:
  postgres:
    image: postgres:alpine3.17
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - db-connection

  backend:
    container_name: backend
    build:
      context: ./..
      dockerfile: src/Dockerfile
    depends_on:
      - postgres
    networks:
      - db-connection

volumes:
  postgres_data:

networks:
  db-connection:
